/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import controllers.QLPhanAnhController;
import java.util.ArrayList;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author trado006
 */
public class QLPhanAnhPanel extends javax.swing.JPanel {

    /**
     * Creates new form QLPhanAnhPanel
     */
    public QLPhanAnhPanel() {
        initComponents();
        qlPhanAnh = new QLPhanAnhController();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        nameTextFiled = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        typeComboBox = new javax.swing.JComboBox<>();
        stateComboBox = new javax.swing.JComboBox<>();
        seachButton = new javax.swing.JToggleButton();
        viewButton = new javax.swing.JToggleButton();
        jLabel5 = new javax.swing.JLabel();
        dateComboBox = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        contentTextpane = new javax.swing.JTextPane();
        deleteButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Quản lí phản ánh");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tìm kiếm phản ánh", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 14))); // NOI18N

        jLabel2.setBackground(new java.awt.Color(204, 204, 204));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("Tên người phản ánh");
        jLabel2.setOpaque(true);

        nameTextFiled.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextFiledActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(204, 204, 204));
        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Loại phản ánh");
        jLabel3.setOpaque(true);

        jLabel4.setBackground(new java.awt.Color(204, 204, 204));
        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("Trạng thái");
        jLabel4.setOpaque(true);

        typeComboBox.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        typeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeComboBoxActionPerformed(evt);
            }
        });

        stateComboBox.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        stateComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stateComboBoxActionPerformed(evt);
            }
        });

        seachButton.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        seachButton.setText("Tìm kiếm");
        seachButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seachButtonActionPerformed(evt);
            }
        });

        viewButton.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        viewButton.setText("Xem");
        viewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewButtonActionPerformed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(204, 204, 204));
        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setText("Ngày phản ánh");
        jLabel5.setOpaque(true);

        dateComboBox.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        dateComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(typeComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nameTextFiled)
                    .addComponent(stateComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dateComboBox, 0, 233, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(viewButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(seachButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(544, 544, 544))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(seachButton, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                    .addComponent(nameTextFiled, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(typeComboBox, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(stateComboBox, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(viewButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                            .addComponent(dateComboBox))
                        .addGap(1, 1, 1))))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nội dung phản ánh", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 14))); // NOI18N

        contentTextpane.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jScrollPane1.setViewportView(contentTextpane);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE)
        );

        deleteButton.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        deleteButton.setText("Xóa");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        saveButton.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        saveButton.setText("Lưu thay đổi");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(saveButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteButton)
                    .addComponent(saveButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    
    QLPhanAnhController qlPhanAnh ;
    
    private void nameTextFiledActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextFiledActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTextFiledActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
        if(!qlPhanAnh.getId()){
            JOptionPane.showMessageDialog(this, "bạn chưa nhập đủ thông tin!","cảnh báo",JOptionPane.WARNING_MESSAGE);
        }else{
            qlPhanAnh.deletePhanAnh();
            JOptionPane.showMessageDialog(this, "successfully!","ok",JOptionPane.OK_OPTION);
            
            typeComboBox.removeAllItems();
            typeComboBox.setSelectedIndex(-1);
            typeComboBox.setSelectedIndex(-1);
            contentTextpane.setText("");
            nameTextFiled.setText("");
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void dateComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateComboBoxActionPerformed
        // TODO add your handling code here:
        if(dateComboBox.getSelectedIndex()==-1){
        }else{
            qlPhanAnh.setDate((String)dateComboBox.getSelectedItem());
        }
    }//GEN-LAST:event_dateComboBoxActionPerformed

    private void seachButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seachButtonActionPerformed
        // TODO add your handling code here:
        if(nameTextFiled.getText().equals("")){
            JOptionPane.showMessageDialog(this, "bạn chưa nhập tên!","cảnh báo",JOptionPane.WARNING_MESSAGE);
        }else{
            switch(qlPhanAnh.setName(nameTextFiled.getText())){
                case -1:
                    JOptionPane.showMessageDialog(this, "kết nối thất bại","cảnh báo",JOptionPane.WARNING_MESSAGE);
                    return;
                case 0:
                    JOptionPane.showMessageDialog(this, "tên nhập không tồn tại \n yêu cầu nhập lại","cảnh báo",JOptionPane.WARNING_MESSAGE);
                    return;
                case 1:
                    JOptionPane.showMessageDialog(this, "tìm kiếm thành công","ok",JOptionPane.OK_OPTION);
                    qlPhanAnh.pretareTypeList();
                    ArrayList<String> typeList = qlPhanAnh.getTypeList();
                    
                    typeComboBox.removeAllItems();
                    typeComboBox.setSelectedIndex(-1);
                    DefaultComboBoxModel<String> typeModel = (DefaultComboBoxModel<String>) typeComboBox.getModel();
                    
                    for(String s:typeList){
                    typeModel.addElement(s);
                    }
                    typeComboBox.setSelectedIndex(-1);
                    stateComboBox.setSelectedIndex(-1);
                    stateComboBox.removeAllItems();
                    
                    dateComboBox.setSelectedIndex(-1);
                    dateComboBox.removeAllItems();
                    
            }
        }
    }//GEN-LAST:event_seachButtonActionPerformed

    private void viewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewButtonActionPerformed
        // TODO add your handling code here:
        if(dateComboBox.getSelectedIndex()==-1){
            JOptionPane.showMessageDialog(this, "bạn chưa nhập đủ thông tin","error",JOptionPane.ERROR_MESSAGE);
            
        }else{
            qlPhanAnh.getId();
            contentTextpane.setText(qlPhanAnh.getContent());
            JOptionPane.showMessageDialog(this, "successfully","ok",JOptionPane.OK_OPTION);
        }
    }//GEN-LAST:event_viewButtonActionPerformed

    private void typeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeComboBoxActionPerformed
        // TODO add your handling code here:
        if(typeComboBox.getSelectedIndex()==-1){
            stateComboBox.setSelectedIndex(-1);
            stateComboBox.removeAllItems();
            stateComboBox.setSelectedIndex(-1);
            dateComboBox.setSelectedIndex(-1);
            dateComboBox.removeAllItems();
            dateComboBox.setSelectedIndex(-1);
        }else{
            qlPhanAnh.setType((String)typeComboBox.getSelectedItem());
            if(qlPhanAnh.prepareStateList()){
            ArrayList<String> stateList = qlPhanAnh.getStateList();
            stateComboBox.removeAllItems();
            DefaultComboBoxModel<String> stateModel =(DefaultComboBoxModel<String>) stateComboBox.getModel();
            stateComboBox.setSelectedIndex(-1);
            
            for(String s:stateList){
                stateModel.addElement(s);
            }
            stateComboBox.setSelectedIndex(-1);
            }else{
                JOptionPane.showMessageDialog(this, "kết nối thất bại","no connection",JOptionPane.ERROR_MESSAGE);
            }
            
        }
    }//GEN-LAST:event_typeComboBoxActionPerformed

    private void stateComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stateComboBoxActionPerformed
        // TODO add your handling code here:
        if(stateComboBox.getSelectedIndex()==-1){
            dateComboBox.setSelectedIndex(-1);
            dateComboBox.removeAllItems();
            dateComboBox.setSelectedIndex(-1);
        }else{
            qlPhanAnh.setState((String)stateComboBox.getSelectedItem());
            qlPhanAnh.prepareDateList();
            ArrayList<String> dateList = qlPhanAnh.getDateList();
            DefaultComboBoxModel<String> dateModel =(DefaultComboBoxModel<String>) dateComboBox.getModel();
            dateComboBox.setSelectedIndex(-1);
            dateComboBox.removeAllItems();
            for(String s:dateList){
                dateModel.addElement(s);
            }
            dateComboBox.setSelectedIndex(-1);
            
            
        }
    }//GEN-LAST:event_stateComboBoxActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
        if(!qlPhanAnh.getId()){
            JOptionPane.showMessageDialog(this, "bạn chưa nhập đủ thông tin!","cảnh báo",JOptionPane.WARNING_MESSAGE);
        }else{
            qlPhanAnh.updateContent(contentTextpane.getText());
            JOptionPane.showMessageDialog(this, "successfully!","ok",JOptionPane.OK_OPTION);
            
        }
    }//GEN-LAST:event_saveButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane contentTextpane;
    private javax.swing.JComboBox<String> dateComboBox;
    private javax.swing.JButton deleteButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nameTextFiled;
    private javax.swing.JButton saveButton;
    private javax.swing.JToggleButton seachButton;
    private javax.swing.JComboBox<String> stateComboBox;
    private javax.swing.JComboBox<String> typeComboBox;
    private javax.swing.JToggleButton viewButton;
    // End of variables declaration//GEN-END:variables
}
