/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import controllers.QLPhanHoiModify;
import javax.swing.JFrame;


/**
 *
 * @author Vostro 3580
 */
public class QLyPhanHoi extends javax.swing.JPanel {
    
    JFrame parentFrame;

    /**
     * Creates new form QLyPhanHoi
     */
    public QLyPhanHoi(JFrame parentFrame) {
        this.parentFrame = parentFrame;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnSearch = new javax.swing.JButton();
        combox = new javax.swing.JComboBox<>();
        txtSearch = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableSearch = new javax.swing.JTable();
        btnXuatPH = new javax.swing.JButton();
        btnGhiNhan = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnSearch.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(102, 0, 102));
        btnSearch.setText("Search");
        btnSearch.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        combox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        combox.setForeground(new java.awt.Color(153, 0, 153));
        combox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mã phản ánh", "Người phản ánh", "Nội dung" }));
        combox.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        combox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboxActionPerformed(evt);
            }
        });

        txtSearch.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(102, 0, 102));
        jButton1.setText("Show");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(combox, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(btnSearch)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(22, 22, 22))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combox, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        tableSearch.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tableSearch.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã phản ánh", "Người phản ánh", "Nội dung", "Ngày phản ánh", "Phân loại", "Trạng thái"
            }
        ));
        jScrollPane1.setViewportView(tableSearch);

        btnXuatPH.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnXuatPH.setForeground(new java.awt.Color(102, 0, 102));
        btnXuatPH.setText("Xuất phản hồi");
        btnXuatPH.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnXuatPH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXuatPHActionPerformed(evt);
            }
        });

        btnGhiNhan.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnGhiNhan.setForeground(new java.awt.Color(102, 0, 102));
        btnGhiNhan.setText("Ghi nhận phản hồi");
        btnGhiNhan.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnGhiNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGhiNhanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 941, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(241, 241, 241)
                        .addComponent(btnXuatPH, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(btnGhiNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGhiNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXuatPH, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );
    }// </editor-fold>//GEN-END:initComponents
    private int id=-1;
    private String header[]={"Mã phản ánh", "Người phản ánh", "Nội dung", "Ngày phản ánh", "Phân loại", "Trạng thái"};
    private DefaultTableModel tblModel=new DefaultTableModel(header,0);
    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        ResultSet rs=null;
        try{
            if(id==-1){
                JOptionPane.showMessageDialog(this, "Bạn chưa chọn tìm kiếm theo tiêu chí !");
                return;
            }
            rs= new QLPhanHoiModify().Search(txtSearch.getText(), id);
            if(rs.isBeforeFirst()==false){
                JOptionPane.showMessageDialog(this, "Không tìm thấy nội dung bạn cần tìm !");
                return;
            }
            Vector data=null;
            tblModel.setRowCount(0);
            while(rs.next()){
                data=new Vector();
                data.add(rs.getInt("MA_PHAN_ANH"));
                data.add(rs.getString("NGUOI_PHAN_ANH"));
                data.add(rs.getString("NOI_DUNG"));
                data.add(rs.getDate("NGAY_PHAN_ANH"));
                data.add(rs.getString("PHAN_LOAI"));
                data.add(rs.getString("TRANG_THAI"));
                tblModel.addRow(data);
            }
            tableSearch.setModel(tblModel);
        }catch(Exception ex){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void comboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboxActionPerformed
        // TODO add your handling code here:
        String selected= combox.getSelectedItem().toString();
        if(selected.equals("Mã phản ánh")){
            id=1;
        }
        if(selected.equals("Người phản ánh")){
            id=2;
        }
        if(selected.equals("Nội dung")){
            id=3;
        }
    }//GEN-LAST:event_comboxActionPerformed

    private void btnXuatPHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXuatPHActionPerformed
        // TODO add your handling code here:
       
        ResultSet rs=null;
        try{
            int selected=tableSearch.getSelectedRow();
            if(selected==-1){
                JOptionPane.showMessageDialog(this, "Chưa có hàng nào được chọn !");
                
            }else{
                String data=tblModel.getValueAt(selected, 0).toString();
                rs= new QLPhanHoiModify().XuatPH(data);
                if(rs.isBeforeFirst()==false){
                    JOptionPane.showMessageDialog(this, "Phản ánh này chưa được ghi nhận phản hồi, hãy ghi nhận trước !");
                    
                }else{
                    String maPH=null, ngayPH=null, ngLQ=null, nd=null, cQ=null;
                    while(rs.next()){
                        maPH=String.valueOf(rs.getInt("MA_PHAN_HOI"));
                        ngayPH=String.valueOf(rs.getDate("NGAY_PHAN_HOI"));
                        ngLQ=String.valueOf(rs.getString("NGUOI_LIEN_QUAN"));
                        nd=String.valueOf(rs.getString("NOI_DUNG"));
                        cQ=String.valueOf(rs.getString("CO_QUAN"));
                    }

                    new XuatPhanHoiFrame(maPH, ngayPH, ngLQ, nd, cQ).setVisible(true);   
                }
            }
        }catch(Exception ex){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnXuatPHActionPerformed

    private void btnGhiNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGhiNhanActionPerformed
        // TODO add your handling code here:
        int selected= tableSearch.getSelectedRow();
        if(selected==-1){
            JOptionPane.showMessageDialog(this, "Không có hàng nào được chọn !");
            return;
        }else{
            String maPA=tblModel.getValueAt(selected, 0).toString();
           try{
                ResultSet rs=new QLPhanHoiModify().GhiNhanPhanHoi(maPA);
                if(rs.isBeforeFirst()){
                   JOptionPane.showMessageDialog(this, "Phản hồi này đã được ghi nhận, bấm xem phản hồi !");
                   return;
                }else{
                    new GhiNhanPhanHoiFrame(maPA).setVisible(true);
                }
           }catch(Exception ex){
               ex.printStackTrace();
           }
        }
        
    }//GEN-LAST:event_btnGhiNhanActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ResultSet rs=null;
        try{
            rs= new QLPhanHoiModify().Show();
            Vector data=null;
            tblModel.setRowCount(0);
            while(rs.next()){
                data=new Vector();
                data.add(rs.getInt("MA_PHAN_ANH"));
                data.add(rs.getString("NGUOI_PHAN_ANH"));
                data.add(rs.getString("NOI_DUNG"));
                data.add(rs.getDate("NGAY_PHAN_ANH"));
                data.add(rs.getString("PHAN_LOAI"));
                data.add(rs.getString("TRANG_THAI"));
                tblModel.addRow(data);
            }
            tableSearch.setModel(tblModel);
        }catch(Exception ex){
            ex.printStackTrace();
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGhiNhan;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnXuatPH;
    private javax.swing.JComboBox<String> combox;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableSearch;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
