/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views.phanhoi;

import views.phananh.*;
import controllers.TimKiemController;
import controllers.phananh.SuaPAController;
import controllers.phananh.XemPAController;
import controllers.phanhoi.PhanHoiController;
import java.awt.BorderLayout;
import java.sql.Date;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import models.PhanAnh;
import models.QLPhanHoi;

/**
 *
 * @author acer
 */
public class PhanHoiPanel extends javax.swing.JPanel {

    JFrame parentFrame;
    private TimKiemController control = new TimKiemController();
    private ArrayList<PhanAnh> listSearch = new ArrayList<>();
    
    DefaultTableModel model;
    
     public PhanHoiPanel(JFrame parentFrame) {
        this.parentFrame = parentFrame;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBoxState = new javax.swing.JComboBox<>();
        jTextName = new javax.swing.JTextField();
        jButtonInsert = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        thongTinPhanHoi = new javax.swing.JTable();
        btnDetail = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxLinhVuc = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                formComponentHidden(evt);
            }
        });

        jComboBoxState.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jComboBoxState.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tất cả", "Môi trường", "Chờ tiếp nhận", "Đang giải quyết", "Đã giải quyết", "Từ chối tiếp nhận", "Bị trả lại", "Chờ bổ sung" }));
        jComboBoxState.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxStateActionPerformed(evt);
            }
        });

        jTextName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextName.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextNameKeyPressed(evt);
            }
        });

        jButtonInsert.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonInsert.setText("Thêm phản hồi");
        jButtonInsert.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInsertActionPerformed(evt);
            }
        });

        thongTinPhanHoi.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        thongTinPhanHoi.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        thongTinPhanHoi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Người phản ánh", "Nội dung", "Ngày", "Phân loại", "Trạng thái"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        thongTinPhanHoi.setRowHeight(28);
        thongTinPhanHoi.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                thongTinPhanHoiComponentHidden(evt);
            }
        });
        jScrollPane1.setViewportView(thongTinPhanHoi);

        btnDetail.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnDetail.setText("Xem chi tiết");
        btnDetail.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetailActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Trạng thái");

        jComboBoxLinhVuc.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBoxLinhVuc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tất cả", "An toàn thực phẩm", "Thủ tục hành chính", "An ninh trật tự", "Tôn giáo tín ngưỡng", "Thi đua khen thưởng", "Văn hóa lễ hội", "Kinh doanh", "Thi hành pháp luật", "Lĩnh vực khác" }));
        jComboBoxLinhVuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxLinhVucActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Lĩnh vực");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Người phản ánh");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 875, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxState, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxLinhVuc, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextName)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxState, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextName, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBoxLinhVuc, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(btnDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(70, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxStateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxStateActionPerformed
        // TODO add your handling code here:
        String state = jComboBoxState.getSelectedItem().toString();
        String linhVuc = jComboBoxLinhVuc.getSelectedItem().toString();
        String name = jTextName.getText();
        if (state == "Tất cả") state = "";
        if (linhVuc == "Tất cả") linhVuc = "";
        listSearch = null;
        listSearch = control.getPhanAnhByAll(state, linhVuc, name);
        model = new DefaultTableModel();
        model = (DefaultTableModel) thongTinPhanHoi.getModel();
        model.setRowCount(0);
        showResult();
    }//GEN-LAST:event_jComboBoxStateActionPerformed

    private void jTextNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextNameKeyPressed
        // TODO add your handling code here:
        String state = jComboBoxState.getSelectedItem().toString();
        String linhVuc = jComboBoxLinhVuc.getSelectedItem().toString();
        String name = jTextName.getText();
        if (state == "Tất cả") state = "";
        if (linhVuc == "Tất cả") linhVuc = "";
        listSearch = null;
        listSearch = control.getPhanAnhByAll(state, linhVuc,name);
        model = new DefaultTableModel();
        model = (DefaultTableModel) thongTinPhanHoi.getModel();
        model.setRowCount(0);
        showResult();
    }//GEN-LAST:event_jTextNameKeyPressed

    private void thongTinPhanHoiComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_thongTinPhanHoiComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_thongTinPhanHoiComponentHidden

    private void jButtonInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInsertActionPerformed
         int selected= thongTinPhanHoi.getSelectedRow();
        if(selected==-1){
            JOptionPane.showMessageDialog(this, "Không có hàng nào được chọn !");
            return;
        }else{
            String maPA=model.getValueAt(selected, 0).toString();
            try{
                ResultSet rs=new PhanHoiController().ghiNhanPhanHoi(maPA);
                if(rs.isBeforeFirst()){
                    JOptionPane.showMessageDialog(this, "Phản hồi này đã được ghi nhận, bấm xem phản hồi !");
                    return;
                }else{
                    this.removeAll();
                    this.setLayout(new BorderLayout());
                    this.add(new ThemPhanHoiPanel(parentFrame, maPA));
                    this.validate();
                    this.repaint();
                }
            }catch(Exception ex){
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_jButtonInsertActionPerformed

    private void btnDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetailActionPerformed
         ResultSet rs=null;
        QLPhanHoi pH=new QLPhanHoi();
        try{
            int selected=thongTinPhanHoi.getSelectedRow();
            if(selected==-1){
                JOptionPane.showMessageDialog(this, "Chưa có hàng nào được chọn !");

            }else{
                String data=model.getValueAt(selected, 0).toString();
                rs= new PhanHoiController().xuatPH(data);
                if(rs.isBeforeFirst()==false){
                    JOptionPane.showMessageDialog(this, "Phản ánh này chưa được ghi nhận phản hồi, hãy ghi nhận trước !");

                }else{
                   
                    while(rs.next()){
                        pH.setMaPhanHoi(rs.getInt("MA_PHAN_HOI"));
                        pH.setNgayPhanHoi(String.valueOf(rs.getDate("NGAY_PHAN_HOI")));
                        pH.setNguoiLienQuan(String.valueOf(rs.getString("NGUOI_LIEN_QUAN")));
                        pH.setNoiDung(String.valueOf(rs.getString("NOI_DUNG")));
                        pH.setCoQuan(String.valueOf(rs.getString("CO_QUAN")));
                    }

                    this.removeAll();
                    this.setLayout(new BorderLayout());
                    this.add(new XemPhanHoiPanel(parentFrame, pH));
                    this.validate();
                    this.repaint();
                }
            }
        }catch(Exception ex){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnDetailActionPerformed

    private void jComboBoxLinhVucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxLinhVucActionPerformed
        String state = jComboBoxState.getSelectedItem().toString();
        String linhVuc = jComboBoxLinhVuc.getSelectedItem().toString();
        String name = jTextName.getText();
        if (state == "Tất cả") state = "";
        if (linhVuc == "Tất cả") linhVuc = "";
        listSearch = null;
        listSearch = control.getPhanAnhByAll(state, linhVuc, name);
        model = new DefaultTableModel();
        model = (DefaultTableModel) thongTinPhanHoi.getModel();
        model.setRowCount(0);
        showResult();
                  
    }//GEN-LAST:event_jComboBoxLinhVucActionPerformed

    private void formComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentHidden
        
    }//GEN-LAST:event_formComponentHidden
    
    public void showResultByDate(){
        if(listSearch.isEmpty())
            JOptionPane.showMessageDialog(thongTinPhanHoi, "Không tồn tại dữ liệu cần tìm");
        for (int i = 0; i < listSearch.size(); i++) {
            model.addRow(new Object[]{listSearch.get(i).getId(),listSearch.get(i).getName(),listSearch.get(i).getContent(),listSearch.get(i).getDate(),listSearch.get(i).getType(),listSearch.get(i).getState()});   
        }
    }
    
    static boolean checkYear(int year) 
    { 
        return (((year % 4 == 0) && (year % 100 != 0)) || 
            (year % 400 == 0)); 
    } 
    
    public void showResultByName(){
        
        for (int i = 0; i < listSearch.size(); i++) {
           
            model.addRow(new Object[]{listSearch.get(i).getName(),listSearch.get(i).getContent(),listSearch.get(i).getDate(),listSearch.get(i).getType(),listSearch.get(i).getState()});   
        }
       
    }
    public void showResult(){
//            if(listSearch.isEmpty()) 
//                JOptionPane.showMessageDialog(thongTinPhanAnh, "Không tồn tại dữ liệu cần tìm");
            for (int i = 0; i < listSearch.size(); i++) {
                model.addRow(new Object[]{listSearch.get(i).getName(),
                                            listSearch.get(i).getContent(),
                                            listSearch.get(i).getDate(),
                                            listSearch.get(i).getType(),
                                            listSearch.get(i).getState()});   
            }
    }

 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDetail;
    private javax.swing.JButton jButtonInsert;
    private javax.swing.JComboBox<String> jComboBoxLinhVuc;
    private javax.swing.JComboBox<String> jComboBoxState;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextName;
    private javax.swing.JTable thongTinPhanHoi;
    // End of variables declaration//GEN-END:variables
}
